name: "Create Jira Issue"
description: "Creates a Jira issue or Sub-task with enhanced security, validation, and enterprise-grade reliability"
author: "Michal Solarek"

branding:
  icon: "plus-square"
  color: "blue"

inputs:
  jira_server:
    description: "The Jira server URL (e.g., https://company.atlassian.net)"
    required: true
  jira_username:
    description: "The Jira username or email address"
    required: true
  jira_api_token:
    description: "The Jira API token (not password!)"
    required: true
  project_key:
    description: "The Jira project key (e.g., PROJ, DEV)"
    required: true
  issue_type:
    description: "The type of the issue"
    required: true
    default: "Task"
  parent_issue_key:
    description: "The key of the parent issue if creating a Sub-task (e.g., PROJ-123)"
    required: false
  assignee:
    description: "Assignee username (optional)"
    required: false
  issue_summary:
    description: "The summary/title of the issue"
    required: true
  issue_description:
    description: "The detailed description of the issue"
    required: true
  issue_priority:
    description: "The priority of the issue"
    required: true
    default: "Medium"
  issue_labels:
    description: "Comma-separated labels for the issue (e.g., bug,frontend,urgent)"
    required: false
  attachment_paths:
    description: "Comma-separated paths of files to attach (e.g., ./logs/error.log,./screenshots/bug.png)"
    required: false
  log_level:
    description: "Logging level for debugging (DEBUG, INFO, WARNING, ERROR)"
    required: false
    default: "INFO"

outputs:
  issue_key:
    description: "The key of the created Jira issue"
  issue_url:
    description: "The URL of the created Jira issue"

runs:
  using: "composite"
  steps:
    - name: Set up Python Environment
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Install Python Dependencies
      id: install-dependencies
      shell: bash
      run: |
        echo "Installing Python dependencies..."
        pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
        echo "Dependencies installed successfully"

    - name: Create Jira Issue
      id: create-jira-issue
      shell: bash
      env:
        # Map GitHub Actions inputs to environment variables for security
        INPUT_JIRA_SERVER: ${{ inputs.jira_server }}
        INPUT_JIRA_USERNAME: ${{ inputs.jira_username }}
        INPUT_JIRA_API_TOKEN: ${{ inputs.jira_api_token }}
        INPUT_PROJECT_KEY: ${{ inputs.project_key }}
        INPUT_ISSUE_TYPE: ${{ inputs.issue_type }}
        INPUT_PARENT_ISSUE_KEY: ${{ inputs.parent_issue_key }}
        INPUT_ASSIGNEE: ${{ inputs.assignee }}
        INPUT_ISSUE_SUMMARY: ${{ inputs.issue_summary }}
        INPUT_ISSUE_DESCRIPTION: ${{ inputs.issue_description }}
        INPUT_ISSUE_PRIORITY: ${{ inputs.issue_priority }}
        INPUT_ISSUE_LABELS: ${{ inputs.issue_labels }}
        INPUT_ATTACHMENT_PATHS: ${{ inputs.attachment_paths }}
        INPUT_LOG_LEVEL: ${{ inputs.log_level }}
        # Python path configuration
        PYTHONPATH: ${{ github.action_path }}/src
      run: |
        echo "Starting Jira issue creation..."
        cd ${{ github.action_path }}
        python src/main.py
        echo "Jira issue creation completed"
